{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  # annotations:
  #   kubed.appscode.com/sync: "true"
type: kubernetes.io/tls
data:
  tls.crt: |
        ZWZsZWhmO2VqYXNmO2VkanNmO2xrc2FkamY7bHNhZGtqZjtsZHNramY7bHNkYWtqZjtsc2Fka2pmO2RzbGtqZjtsc2RhamtuZjtkc2xramY7YXNkbGtqZmRsO3Nhaw==
  tls.key: |
        ZGZqbnNkO2xmamZkaGdmb2Rpc29rZmpkbmFzbGtmamE7bHNka2Znam5hcztkbGY7bHNkbnNzZGRrZGtrZA==
{{ end }}